
#数据源
spring:
  datasource:
    druid:
      driver-class-name:  com.mysql.cj.jdbc.Driver
      #url: jdbc:mysql://localhost:3306/blog?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf-8&autoReconnect=true
      url: jdbc:mysql://47.100.220.147:3306/blog?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      username: root
      password: 1234
mybatis:
  type-aliases-package: com/ekko/myblog/pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    root: info
    com.ekko.myblog: warn
  file:
    name: log/blog-pro.log
server:
  port: 80
